import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";

import AppProviders from "@/providers/AppProviders";
import Header from "@/components/shared/Header";

import CategoriesProvider from "@/providers/client/CategoriesProvider";
import { getCategories, getPosts } from "@/repositories";
import PostsProvider from "@/providers/client/PostsProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = (await getCategories()) || [];
  const posts = (await getPosts()) || [];
  return (
    <html lang="ru" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProviders>
          <CategoriesProvider categories={categories}>
            <PostsProvider posts={posts}>
              <Header />
              {children}
            </PostsProvider>
          </CategoriesProvider>
        </AppProviders>
      </body>
    </html>
  );
}
