import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";

import AppProviders from "@/providers/AppProviders";
import Header from "@/components/shared/Header";

import CategoriesProvider from "@/providers/client/CategoriesProvider";
import { getCategories } from "@/repositories";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = (await getCategories()) || [];
  return (
    <html lang="ru" suppressHydrationWarning>
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, viewport-fit=cover"
        />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProviders>
          <CategoriesProvider categories={categories}>
            <Header />
            {children}
          </CategoriesProvider>
        </AppProviders>
      </body>
    </html>
  );
}
